blank_issues_enabled: false
contact_links:
  - name: 鸿蒙官方社区
    url: https://www.openharmony.cn/mainPlay
    about: 开启 OpenHarmony 之旅吧！
  - name: 行为守则
    url: https://www.openharmony.cn/rule/
    about: OpenHarmony社区遵守开源社区行为守则
    